In [1]:
from Functions._createModel import *
from Functions._analyzeData import *
from Functions._editDatabase import getTransactionData, getAccount

from matplotlib import pyplot as plt

In [2]:
DATA = getTimeCycle(getTransactionData(getAccount("atlas")), "DAY")

In [3]:
budget = DATA["TOTAL"].cumsum()
budget.index = pd.to_datetime(DATA.index)
budget = budget.to_frame(name='TOTAL')
budget = addFeatures(budget)

budget = budget.rename(columns={"TOTAL": "Budget"})

budget

                 Budget  Hour  DoW  Quarter  Month  Year  DoY
DAY
2000-01-01    -168000.0     0    5        1      1  2000    1
2000-01-02    -248000.0     0    6        1      1  2000    2
2000-01-03    -480000.0     0    0        1      1  2000    3
2000-01-04    -620000.0     0    1        1      1  2000    4
2000-01-05    -752000.0     0    2        1      1  2000    5
...                 ...   ...  ...      ...    ...   ...  ...
2023-12-26  178941000.0     0    1        4     12  2023  360
2023-12-27  178835000.0     0    2        4     12  2023  361
2023-12-28  178701000.0     0    3        4     12  2023  362
2023-12-29  178607000.0     0    4        4     12  2023  363
2023-12-30  178356000.0     0    5        4     12  2023  364

[8765 rows x 7 columns]

In [4]:
model, history, metric = generateModel(budget)

Epoch 1/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 11s 19ms/step - loss: 103789654234365952.0000 - val_loss: 315982324514684928.0000 - learning_rate: 0.0010
Epoch 2/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 104942509355958272.0000 - val_loss: 315982221435469824.0000 - learning_rate: 0.0010
Epoch 3/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 103280125084172288.0000 - val_loss: 315982118356254720.0000 - learning_rate: 0.0010
Epoch 4/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 102237470233460736.0000 - val_loss: 315982015277039616.0000 - learning_rate: 0.0010
Epoch 5/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 105872232336588800.0000 - val_loss: 315981912197824512.0000 - learning_rate: 0.0010
Epoch 6/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 103651931813052416.0000 - val_loss: 315981740399132672.0000 - learning_rate: 0.0010
Epoch 7/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 103662652051423232.0000 - val_loss: 315981431161487360.0000 - learning_rate: 0.0010
Epoch 8/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 102424627728351232.0000 - val_loss: 315981225003057152.0000 - learning_rate: 0.0010
Epoch 9/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - loss: 101053605447991296.0000 - val_loss: 315981121923842048.0000 - learning_rate: 0.0010
Epoch 10/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - loss: 102161664060686336.0000 - val_loss: 315980950125150208.0000 - learning_rate: 0.0010
Epoch 11/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - loss: 105076752853762048.0000 - val_loss: 315980469088813056.0000 - learning_rate: 0.0010
Epoch 12/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - loss: 104116767533563904.0000 - val_loss: 315980331649859584.0000 - learning_rate: 0.0010
Epoch 13/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 101264325133467648.0000 - val_loss: 315980091131691008.0000 - learning_rate: 0.0010
Epoch 14/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 102676613459607552.0000 - val_loss: 315979781894045696.0000 - learning_rate: 0.0010
Epoch 15/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 103115241289678848.0000 - val_loss: 315979541375877120.0000 - learning_rate: 0.0010
Epoch 16/100
159/220 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 101520820580384768.0000

In [ ]:
loss = history.history["loss"]
val_loss = history.history["val_loss"]

plt.figure(figsize=(12, 6))
plt.plot(loss, label="Training Loss")
plt.plot(val_loss, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.grid(True)
plt.legend()
plt.title("Training and Validation Loss")
plt.show()